version: '2'

services:
    giffer_frontend:
        build:
            context: .
            dockerfile: frontend.dockerfile
        image: giffer_frontend
        ports:
            - 3000:3000
        volumes:
            - /opt/download:/opt/download
        environment:
            - NODE_ENV=production
        command: "yarn serve -s /opt/download -l 80"
